// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"context"
	"github.com/google/go-github/v27/github"
	"github.com/rerost/query-recipe-api/infra/data"
	"github.com/rerost/query-recipe-api/infra/search"
	"github.com/rerost/query-recipe-api/repo/snippet"
	"golang.org/x/oauth2"
)

// Injectors from wire.go:

func NewRepo(contextContext context.Context, diConfig Config) snippet.Repo {
	token := ProvidorToken(diConfig)
	tokenSource := oauth2.StaticTokenSource(token)
	client := oauth2.NewClient(contextContext, tokenSource)
	githubClient := github.NewClient(client)
	searchConfig := ProvidorSearchConfig(diConfig)
	searchClient := search.NewGHClient(githubClient, searchConfig)
	dataConfig := ProvidorDataConfig(diConfig)
	dataClient := data.NewGHClient(githubClient, dataConfig)
	repo := snippet.NewRepo(searchClient, dataClient)
	return repo
}
