// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package type_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GithubMetadata struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Repository           string   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubMetadata) Reset()         { *m = GithubMetadata{} }
func (m *GithubMetadata) String() string { return proto.CompactTextString(m) }
func (*GithubMetadata) ProtoMessage()    {}
func (*GithubMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *GithubMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubMetadata.Unmarshal(m, b)
}
func (m *GithubMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubMetadata.Marshal(b, m, deterministic)
}
func (m *GithubMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubMetadata.Merge(m, src)
}
func (m *GithubMetadata) XXX_Size() int {
	return xxx_messageInfo_GithubMetadata.Size(m)
}
func (m *GithubMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GithubMetadata proto.InternalMessageInfo

func (m *GithubMetadata) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GithubMetadata) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GithubMetadata) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func init() {
	proto.RegisterType((*GithubMetadata)(nil), "rerost.query_recipe_api.type.GithubMetadata")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x29, 0x4a, 0x2d, 0xca,
	0x2f, 0x2e, 0xd1, 0x2b, 0x2c, 0x4d, 0x2d, 0xaa, 0x8c, 0x2f, 0x4a, 0x4d, 0xce, 0x2c, 0x48, 0x8d,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0xa9, 0x2c, 0x48, 0x55, 0xca, 0xe4, 0xe2, 0x73, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xf2, 0x85, 0xea, 0x12, 0x52, 0xe4, 0xe2, 0x49, 0x4c, 0x4e, 0x4e, 0x2d, 0x2e, 0x8e,
	0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x86, 0x88, 0x85,
	0x80, 0x84, 0x84, 0x44, 0xb8, 0x58, 0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x24, 0x98, 0xc0, 0x72, 0x10,
	0x8e, 0x90, 0x1c, 0x17, 0x57, 0x51, 0x6a, 0x41, 0x7e, 0x71, 0x66, 0x49, 0x7e, 0x51, 0xa5, 0x04,
	0x33, 0x58, 0x0a, 0x49, 0xc4, 0xc9, 0x34, 0xca, 0x38, 0x1d, 0x6c, 0x95, 0x5e, 0x72, 0x7e, 0xae,
	0x3e, 0xc4, 0x55, 0xfa, 0x60, 0x57, 0xe9, 0x42, 0x5c, 0xa5, 0x9b, 0x58, 0x90, 0xa9, 0x0f, 0xc2,
	0x20, 0x97, 0x59, 0x83, 0x88, 0xf8, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x37, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0xc7, 0xc6, 0x32, 0xd8, 0x00, 0x00, 0x00,
}
